# Generated by Django 5.2.7 on 2025-12-14 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución Estimada')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('estado_prestamo', models.CharField(choices=[('VIGENTE', 'Vigente'), ('DEVUELTO', 'Devuelto'), ('ATRASADO', 'Atrasado')], default='VIGENTE', editable=False, max_length=20, verbose_name='Estado del Préstamo')),
                ('renovado', models.BooleanField(default=False, verbose_name='¿Fue renovado?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
    ]
