# Generated by Django 5.2.7 on 2025-12-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
    ]
