# Generated by Django 5.2.7 on 2025-12-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='estado',
            new_name='activo',
        ),
    ]
