# Generated by Django 5.2.8 on 2026-07-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_categoria_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
